### ISSUE TITLE
`unicode_names2::character("BACKSPACE")` returns None

### ISSUE THREAD

**Issue by youknowone** [progval/unicode_names2#11]
I'd like to check if this is intended design or a bug.

If it is an intended design, I'd like to know adding them as another new API to this crate is okay or it belongs to other crate's responsibility.

Thanks!

**Comment by progval** [comment]
I don't know (I didn't originally write the crate), but I don't see any reason not to support it.

**Comment by DimitrisJim** [comment]
>  but I don't see any reason not to support it.

I think the original author might have released unicode_names right around the time aliases were being added to unicodedata (which it takes inspiration from). So that *might* be the reason why they weren't supported.
