### ISSUE TITLE
Projects using unicode_names2 as a dependency mark it as dirty and repeatedly rebuild it.

### ISSUE THREAD

**Issue by eli-schwartz** [progval/unicode_names2#37]
Ref. https://github.com/progval/unicode_names2/issues/26#issuecomment-1987099164

build.rs says:

```
    println!("cargo:rerun-if-changed=generator/");
```
But https://crates.io/api/v1/crates/unicode_names2/1.1.0/download https://crates.io/api/v1/crates/unicode_names2/1.2.1/download etc. doesn't contain that directory.

```
       Dirty unicode_names2 v1.2.1: the file `/var/tmp/portage/dev-util/ruff-0.3.0/work/cargo_home/gentoo/unicode_names2-1.2.1/generator/` is missing
```

**Comment by progval** [comment]
Resolved in v1.2.2, thanks for the report
